### ISSUE TITLE
mkdir /argo/outputs: permission denied error 

### ISSUE THREAD

**Issue by sjbylo** [opendatahub-io/manifests#17]
When running example pipeline, e.g. "artifact-passing", get the error:

“child 'artifact-passing-b2j7k-1148074540' failed”
“executor error: mkdir /argo/outputs: permission denied”. 

Workaround is:

```
oc adm policy add-scc-to-user anyuid -z pipeline-runner -n kubeflow
```

I think this bug is to do with using the k8sapi executor and arg?  It has been fixed in a recent version of argo, which should be fixed in KF 1.0 (although I could not verify this).  Please correct me if I'm wrong. 

Argo example with empyDir:

```
# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /dir/hello_world.txt"]
      volumeMounts:
      - name: workdir
        mountPath: /dir
    outputs:
      artifacts:
      - name: hello-art
        path: /dir/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /dir/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /dir/message"]
      volumeMounts:
      - name: workdir
        mountPath: /dir
```
